server:
  port: 8080
#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/f_user?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
    #延迟初始化   或 配合 @Lazy(value = true)  注解在bean上
  #    lazy-initialization: true
  banner:
    location: banner.txt

mybatis:
  type-aliases-package: com.liuqi.cj.easyspringboot.demo.entity.*
  #下划线和驼峰转换
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    cache-enabled: true
    call-setters-on-nulls: true
  mapper-locations: classpath:mapper/*.xml




# 日志信息输出
logging:
  level:
    com.liuqi.cj.easyspringboot: debug
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug
            StatementCreatorUtils: trace


#文件过滤器启用
filter:
  loginFilter: true
